# Generated by Django 5.0.1 on 2024-02-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='music',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='music',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='music',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='music',
            name='rating',
        ),
    ]
