# Generated by Django 5.0.1 on 2024-02-12 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_music_created_at_remove_music_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='music',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
