# Generated by Django 5.0.1 on 2024-02-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_created_at_music_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='genres',
        ),
    ]
