# Generated by Django 5.0.1 on 2024-02-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_artist_genre_alter_music_album_album_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=200),
        ),
        migrations.AddField(
            model_name='music',
            name='genres',
            field=models.ManyToManyField(to='music.genre'),
        ),
    ]
