# Generated by Django 5.0.1 on 2024-02-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_music_category_music_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
