# Generated by Django 5.0.1 on 2024-02-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_music_created_at_alter_music_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='music',
            name='genres',
        ),
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='music',
            name='genres',
            field=models.CharField(default='', max_length=200),
        ),
    ]
