# Generated by Django 5.0.1 on 2024-02-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_artist_genre_alter_music_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='music',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='music',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='music',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
