# Generated by Django 5.0.1 on 2024-02-13 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_music_album_alter_music_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='music',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
