# Generated by Django 5.0.1 on 2024-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_music_created_at_music_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
