# Generated by Django 5.0.1 on 2024-02-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_music_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='music',
            name='modified_at',
        ),
    ]
