# Generated by Django 5.0.1 on 2024-02-13 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_remove_music_created_at_remove_music_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='music',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
